### ISSUE TITLE
[BUG] Repeat combinator fixes

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#1035]
`RepeatCombinator` expects:

1. `inner`: JAXGenerativeFunction
2. `repeats`: Int = Pytree.static()
However `map_combinator` returns `RepeatCombinator(repeats, f)`. I fixed that to `RepeatCombinator(f, repeats)`.

Furthermore `RepeatTrace` didn't have a `gen_fn` field and no getter either. 

I fixed those here:
https://github.com/probcomp/genjax/compare/nightly...mkl-repeat-combinator

**Comment by mirkoklukas** [comment]
@femtomc @sritchie Should I open a PR with this? We have quite a few use cases for the `repeat_combinator`; it can be annoying mimicking that with map.

**Comment by femtomc** [comment]
Yes, please.

**Comment by femtomc** [comment]
Closed by #1037.
