### ISSUE TITLE
[Docs] Docstring for ScanCombinator seems broken?

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#1171]
[In the example](https://github.com/probcomp/genjax/blob/3365aa1fc1d1540e36eff81785f65576557b5e99/src/genjax/_src/generative_functions/combinators/scan.py#L133,) you give an example of a `next_step` function for scan that takes only a single input. 

I don't see how this can ever be scanned over, since [the implementation](https://github.com/probcomp/genjax/blob/3365aa1fc1d1540e36eff81785f65576557b5e99/src/genjax/_src/generative_functions/combinators/scan.py#L189) seems like it will always call the inner function with two arguments? And indeed the "similar" example immediately below has a function with two arguments.

**Comment by femtomc** [comment]
@sritchie Can you take a look at this? I don't remember if I wrote this docstring, or if this was a recent change.

**Comment by sritchie** [comment]
Good catch! @femtomc the issue is that `random_walk` is defined twice, and the second one (correct) overwrites the first (incorrect). not a recent change, but that's why it didn't break the build. 

Fixed by #1172 .
