### ISSUE TITLE
Tidy up and document ways of creating ChoiceMaps (d, kw, builder etc)

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1178]
We have some test scripts in ChiSight that construct one choicemap in the whole file.  It might be nice in such files to be able to write `genjax.C.d({...choicemap construction...})` rather than either needing to add an import line `from genjax import ChoiceMapBuilder as C` at the top, or needing to write out `genjax.ChoiceMapBuilder.d({...choicemap construction...})` or `genjax.ChoiceMap.d({...choicemap construction...})`.

Feel free to shoot this down -- it is arguably too terse.

**Comment by arijit-dasgupta** [comment]
@georgematheos Out of curiosity, what's the downside of just having the import one liner?
`from genjax import ChoiceMapBuilder as C`

**Comment by sritchie** [comment]
Hey @georgematheos , I don't think it gets better than `genjax.ChoiceMap.d`, which is what I'll propose you use after #1305 is merged. Closing this, let's use the PR for further discussion!
