### ISSUE TITLE
[BUG] jax.jit with a static argument of a `genjax.Pytree.const(list)` causes an error

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1179]
```python
import jax
import genjax

def foo(x):
  return x.const[0] + 1
jfoo = jax.jit(foo, static_argnums=(0,))

jfoo(genjax.Pytree.const([2])) # causes `ValueError: Non-hashable static arguments are not supported. An error occurred while trying to hash an object of type <class 'genjax._src.core.pytree.Const'>, Const(const=[2]).`
```

@nishadgothoskar has used a pattern like this in `b3d/`.  We should look into if there is a better way to structure this part of the code in genjax 0.4.0, but I wanted to document this in case it is a bug and reflects a failure of compositionality.

**Comment by georgematheos** [comment]
Edit: it looks like this is not genjax related.  The following also fails:
```python
import jax
def foo(x):
  return x[0] + 1
jfoo = jax.jit(foo, static_argnums=(0,))
jfoo([2]) # ValueError: Non-hashable static arguments are not supported. An error occurred while trying to hash an object of type <class 'list'>, [3].
```

Maybe what happened is that in genjax 0.3, the hash function for `genjax.Pytree.Const` didn't hash the internal object, which is why this issue did not occur previously.

**Comment by sritchie** [comment]
Thanks for looking into this more closely @georgematheos!
