### ISSUE TITLE
[Docs] Improve documentation for `Constraint` as an `UpdateProblem`

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1180]
I have a few questions about the current documentation for `Constraint`, and what type of `UpdateProblem` a constraint is.
1. Can I call `trace.update(key, Constraint)` to update a given trace?  (Presumably this is allowed?)
2. 2. If so, what is the previous target corresponding to this update?  
3. One thing this question entails is: what is the change to the arguments induced by this Update?  Presumably there is no change?

**Comment by femtomc** [comment]
@georgematheos in a PR I’ll submit next week, I want to clarify the type hierarchy — I think one change should be to remove constraint as a subtype of update request — and have standard update requests which lift constraint to an update request.

**Comment by sritchie** [comment]
@georgematheos I'm going to close this (sorry it's taken so long for us to get back here) in favor of the `edit` work, which @femtomc is pushing on over at #1299. Let me know if this is okay, and re-open if you want me to push on this this week. I have time for it, I am just trying to prioritize edit work and other bugs we're fixing.
