### ISSUE TITLE
[BUG] `genjax.uniform.logpdf` on vectors returns a vector, not a float.

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1181]
Minimal working example:
```
import genjax
x = genjax.uniform.logpdf(jnp.array([0.5, 0.5, 0.5]), jnp.zeros(3), jnp.ones(3))
# The value of x is [0., 0., 0.], but it should be 0.
```

@sritchie I think this is a relatively high priority fix.  I will try to introduce a custom `uniform` distribution into the b3d repo in the meantime so this does not block porting the repo to 0.4.

**Comment by georgematheos** [comment]
Looks like this may be an issue with all `tfp_distributions`.

**Comment by sritchie** [comment]
This is now "fixed" — `logpdf` as called here will still vectorize, since that's what tfp does. But now, if you use `genjax.normal` and friends, we'll throw a type error on a vector instead of broadcasting.
