### ISSUE TITLE
[Defactor] nested map combinator produces confusing representation

### ISSUE THREAD

**Issue by MathieuHuot** [genjax-community/genjax#1220]
From discussion with Pavel: https://probcomp.slack.com/archives/C06EV7GHCCW/p1720640939519139
a nested map combinator produces something counter intuitive that is very error prone.

```python
import genjax
import jax.random as random
import jax.numpy as jnp

model = genjax.gen(lambda pixel: genjax.normal(pixel, 1.0) @ "new_pixel")
vmapped = model.vmap(in_axes=(0,)).vmap(in_axes=(0,))

key = random.PRNGKey(0)
image = jnp.zeros([4, 4], dtype=jnp.float32)
trace = vmapped.simulate(key, (image,))
trace.get_sample()
```
The produced choice map looks like this
<img width="937" alt="Screenshot 2024-07-12 at 11 29 13" src="https://github.com/user-attachments/assets/f5412eeb-e94a-4016-bfc2-c235e50179b6">
where the strange part is `addr=<jax.Array int32(4, 4)`.

**Comment by femtomc** [comment]
Why is that strange? It's completely consistent with `vmap`

Is the question -- should be allocating the index arrays? That's a valid question! But I don't find this behavior strange at all

**Comment by MathieuHuot** [comment]
I think the produced and expected part is that you go from a scalar to a (4,4) value choice map.
Accessing the trace is also fine as you can go `[2,3,"new_pixel"]`. The confusing part is choice map creation where you cannot easily do  something like (and Jaxify it) to use in model.importance:
```
chm = C.n()
for i in range(4):
   for j in range (4)
     chm = chm ^ C.at[i,j,"new_pixel"].set(3.14)
```
or at least I don't know how to get that to work.

**Comment by femtomc** [comment]
I agree re -- choice map creation, we'd like a convenient set of idioms. There is one in the documentation -- using `vmap` to create a choice map:

```python
jax.vmap(lambda idx, v: C.at[idx].set(v))
```

which can be nested, etc.

**Comment by MathieuHuot** [comment]
> I agree re -- choice map creation, we'd like a convenient set of idioms. There is one in the documentation -- using `vmap` to create a choice map:
> 
> ```python
> jax.vmap(lambda idx, v: C.at[idx].set(v))
> ```
> 
> which can be nested, etc.

Ah right, nice! At least I'll add this example to the cookbook on choicemap selection/creation I'm drafting.

**Comment by sritchie** [comment]
@MathieuHuot I don't think we need `vmap` here:

```python
In [1]: import jax.numpy as jnp
In [2]: from genjax import ChoiceMapBuilder as C
In [3]: new_image = jnp.ones([4,4])
In [4]: C[jnp.arange(4), jnp.indices((4,4))[1], "new_pixel"].set(new_image)
Out[4]: 
IdxChm(
  addr=<jax.Array([0, 1, 2, 3], dtype=int32)>,
  c=IdxChm(
    addr=# jax.Array int32(4, 4) [≥0, ≤3] zero:4 nonzero:12
      Array([[0, 1, 2, 3],
             [0, 1, 2, 3],
             [0, 1, 2, 3],
             [0, 1, 2, 3]], dtype=int32)
    ,
    c=StaticChm(
      addr='new_pixel',
      c=ValueChm(
        v=<jax.Array float32(4, 4) ≈1.0 ±0.0 [≥1.0, ≤1.0] nonzero:16>,
      ),
    ),
  ),
)
```

This lets you set the pixels all at once. Or we can vmap if we want to call a function to get values for the specific pixels.

**Comment by sritchie** [comment]
I think this is all okay:

- `model` expects a single mean value for a pixel and traces `"new_pixel"`
- `model.vmap()` traces a vector of pixels at a time
- `model.vmap().vmap()` traces a vector of vectors

So the outer index is the row, and the inner index is the column.

Coming up with the indices is annoying for sure.

**Comment by sritchie** [comment]
Here's how I see to do this with `jax.vmap`:

```python
from genjax import ChoiceMapBuilder as C
import jax.numpy as jnp

jax.vmap(lambda i: C[i].set(
    jax.vmap(lambda j: C[j].set(1.0))(jnp.arange(4))
))(jnp.arange(4))
```
