### ISSUE TITLE
Finally requesting proper access

### ISSUE THREAD

**Issue by ahiser1117** [genjax-community/genjax#1221]
Finally getting around to installing correctly. Started getting version issues with incorrect install.

**Comment by sritchie** [comment]
Hey @ahiser1117 ! This is now self-serve... I'll update the README next week. Let me know if this works for you: https://probcomp.slack.com/archives/C06KP17ATJR/p1719869073052369

**Comment by ahiser1117** [comment]
@sritchie the link did not work...

**Comment by ahiser1117** [comment]
nvm figured it out
