### ISSUE TITLE
[BUG] the system is too permissive in importance sampling

### ISSUE THREAD

**Issue by MathieuHuot** [genjax-community/genjax#1235]
**Describe the bug**

When a trace generated from a proposal has extra variables that a model doesn't accept, it should return an error and not silently continue, even when it may actually do the correct thing. Users should explicitly use the `marginal` construct in these cases.

**To Reproduce**
```
import genjax
import jax
import jax.numpy as jnp
from genjax import ChoiceMapBuilder as C
from genjax import SelectionBuilder as S
from genjax import Target, gen, pretty, switch

@gen
def model():
    x = genjax.normal(0., 1.) @ "x"
    return x

@gen
def proposal(target: Target):
    y = genjax.normal(0., 1.) @ "y"
    return y

target = Target(model, (), C.n())

k_particles = 500
alg = genjax.smc.ImportanceK(
    target, q=proposal.marginal(), k_particles=k_particles
)

key = jax.random.PRNGKey(0)
alg.simulate(key, (target,))
```

**Expected behavior**
This should return an error of the form: choice map from `proposal` contains `"z"` which is not a traced variable from `model`.

**Comment by sritchie** [comment]
Closing as duplicate of #631 .
