### ISSUE TITLE
[Docs] Fix some errors in cookbook entries due to code refactor 

### ISSUE THREAD

**Issue by MathieuHuot** [genjax-community/genjax#1237]
I caught one in the `iterating_computation` one but I'll do a full pass in a bit.

**Comment by sritchie** [comment]
@MathieuHuot hmm, did CI not catch this?

**Comment by MathieuHuot** [comment]
@sritchie hmmm this is strange. I killed the instance and switched to another branch and now I can't reproduce the error. 
The reason I thought there was gonna be an error is that next to me Eric wrote a model using a nested `vmap` combinator very similar to my example and while I would access it as `tr.get_sample()[0, 0, "new_pixel"]`, he would access his as  `tr.get_sample()["new_pixel",0,0]`. And right at this moment when I tried to run the version from the cookbook it was erroring. 

Eric also commented that it felt more natural to him to access it via `tr.get_sample()["new_pixel",0,0]`. I also saw Pavel use the same access pattern.

**Comment by MathieuHuot** [comment]
So maybe it asks for a consistency check in how we create hierarchical choice maps, especially for combinators that introduce unnamed indices like `repeat`, `vmap`, ... which should presumably always push the integer index to the innermost level that is not an integer index or something like that? (trying to say it should perhaps always be `["new_pixel",0,0]` where the first 0 comes from the outer `vmap`).

**Comment by MathieuHuot** [comment]
As I can't reproduce this anymore I'll close this issue.
