### ISSUE TITLE
[Docs] Docs should never reuse PRNGKeys.

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#1249]
I've been looking through the cookbook (trying to figure out how `update` works, and the two examples I look at *both* reuse the PRNGKey:

https://genjax.gen.dev/cookbook/cookbook/basics/methods_of_generative_fun.html (the update section)
https://genjax.gen.dev/cookbook/cookbook/inference/mcmc.html

This is extremely dangerous because it can easily lead to wrong results. We should always model proper PRNGKey hygiene.

**Comment by MathieuHuot** [comment]
Totally agreed Rif. I'll make a pass through the whole set of cookbook entries to fix that.
