### ISSUE TITLE
[Defactor] Better user interfaces on batched traces

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#1269]
Related to #1264.

> I have a good idea for how to fix these "batched" problems with traces permanently, which I'll update via a PR today or tomorrow.

Simple idea: change the trace `@abstractmethod` names, and have `Trace.get_sample()` & `Trace.get_choices()` automatically detect if the trace is batched (by checking the score), and either do the `vmap`, or don't do the `vmap`.

**Comment by sritchie** [comment]
See the duplicate [GEN-553](https://linear.app/chi-fro/issue/GEN-553/enable-get-sample-of-a-vmapped-trace) for more notes from @colin.
