### ISSUE TITLE
[Docs] Add examples of creating choicemaps for use with vmapped models (GEN-568)

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1309]
From our ChiSight work, the question arose: "how do I construct a choicemap to update a value stored in a vmap combinator"?  Some of us knew how to do this so it isn't blocking -- but I didn't see a clear example of this in the docs.  I may have missed something.  So this issue is to either (1) add examples in the docs showing how to do constrained updates or generation with the vmap combinator (and similar), or (2) make it easier to find these examples when searching things like "update vmap combinator" or "vmap choicemap" or "index choicemap" or "choicemap construction".

**Comment by sritchie** [comment]
Sounds good, we definitely want to make this easier to find.

The answer now is to vmap, as discussed in #1220.

**Comment by sritchie** [comment]
The idiom is basically

```python
jax.vmap(lambda idx, v: C[idx].set(v))(jnp.arange(4), values)
```

Or just 

```python
C[jnp.arange(4)].set(values)
```

The nested case in one shot is more annoying, since you need to generate a row of duplicate indices:

```python
In [1]: import jax.numpy as jnp
In [2]: from genjax import ChoiceMapBuilder as C
In [3]: new_image = jnp.ones([4,4])
In [4]: C[jnp.arange(4), jnp.indices((4,4))[1], "new_pixel"].set(new_image)
Out[4]: 
IdxChm(
  addr=<jax.Array([0, 1, 2, 3], dtype=int32)>,
  c=IdxChm(
    addr=# jax.Array int32(4, 4) [≥0, ≤3] zero:4 nonzero:12
      Array([[0, 1, 2, 3],
             [0, 1, 2, 3],
             [0, 1, 2, 3],
             [0, 1, 2, 3]], dtype=int32)
    ,
    c=StaticChm(
      addr='new_pixel',
      c=ValueChm(
        v=<jax.Array float32(4, 4) ≈1.0 ±0.0 [≥1.0, ≤1.0] nonzero:16>,
      ),
    ),
  ),
)
```

This definitely needs to improve. We'll work on this as part of #1307 .

**Comment by sritchie** [comment]
@georgematheos , once we merge #1392 you'll be able to write, e.g.,

```python
C[:, "x", :].set(<your_2d_array>)
```

wdyt?

**Comment by sritchie** [comment]
I know this is not quite the constrained updates case. If you give me an example of a constrained update I can help out here.

**Comment by georgematheos** [comment]
This syntax would be excellent!

This issue was mostly about making sure it is easy to understand how to update a trace from a model using the `vmap` or `scan` combinator by looking at the docs.  (So no new syntax is needed to resolve this issue as I had intended to scope it -- just a documentation change.  But this new syntax looks so good and would be an excellent addition as well!)
