### ISSUE TITLE
[BUG] backward problems are broken (more info coming)

### ISSUE THREAD

**Issue by sritchie** [genjax-community/genjax#1312]
Here is the smoking gun: https://github.com/probcomp/genjax/blob/main/src/genjax/_src/generative_functions/static.py#L551

More info coming soon once we finish up pairing. I think this affects every call to `ChoiceMap.entry` supplied with an `UpdateProblem` that is NOT a `ChoiceMap`.

**Comment by femtomc** [comment]
Fixed in #1322.
