### ISSUE TITLE
[BUG] Treescope HTML rendering font should be same as code

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#1333]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/ffc99baf-59f9-46c1-bfcf-f5b840209646">

**Comment by sritchie** [comment]
I don't know if I agree with this one… do you mean just on the website, not necessarily in the notebok?

@huebert, any CSS wizardry thoughts on how we can get this done on the site?

**Comment by femtomc** [comment]
I set this to work that way before, and something broke it.

I believe we just need to set the `.treescope_root` class to inherit the font (Berkeley Mono) used for the code.

**Comment by femtomc** [comment]
I just tried the above, I think penzai changed the way the HTML results are rendered, as this change doesn't work.

**Comment by mhuebert** [comment]
penzai extracted treescope to [its own repo](https://github.com/google-deepmind/treescope), and the latest versions use shadow DOM to encapsulate/isolate the js/css. I've filed a [pull request](https://github.com/google-deepmind/treescope/pull/38) to add a [part attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_shadow_parts) to the root element which would allow us to target it via css again.

**Comment by sritchie** [comment]
I've got a PR upgrading us to this new treescope [https://github.com/probcomp/genjax/pull/1334](https://github.com/probcomp/genjax/pull/1334) so we can move on this when they fix the bug…

**Comment by sritchie** [comment]
@mhuebert boom, we're on the latest treescope now so we can respond when they add this.
