### ISSUE TITLE
[BUG] Cookbook CSS and code rendering broken

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#1339]
<img width="823" alt="image" src="https://github.com/user-attachments/assets/a7f6e436-a1b6-4451-85bd-79e88c343877">

**Comment by sritchie** [comment]
Is this back?? I thought @huebert had fixed this, maybe we goofed and reverted?

**Comment by femtomc** [comment]
I think the original fix may not have worked

**Comment by femtomc** [comment]
Also, interactivity is fully broken on mobile

**Comment by sritchie** [comment]
I think we're fixed now.
