### ISSUE TITLE
Perhaps the dimap post function should accept the original args as input?

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#1424]
When constructing a `dimap` combinator, the `post` function accepts `(args, retval)` and returns `retval`.  However, the `args` it accepts are the args _after_ running `pre`.  Thus, when `pre` drops information that is in the original arguments passed into the dimap combinator, the post function has no way to include this dropped information in the retval.

Maybe the signature for `post` should be `(args_before_preprocessing, args_after_preprocessing, retval) -> postprocessed_retval`?

E.g.
```python
@gen 
def f(x):
    return x + 1
f.dimap(
    pre=(lambda x, y: (x,)),
    post=(lambda inargs, ret: inargs)
)(1, 2)(PRNGKey(0))
# prints (1,) -- not (1, 2).
```

Happy to share some more realistic use cases if that's helpful.

**Comment by georgematheos** [comment]
@sritchie maybe something you'd be interested in?

**Comment by sritchie** [comment]
I'm fine with that! I like it…

* the user can always re-run the `pre` function if they want…
* we could add a keyword arg for this? or take both?

but that feels indecisive. I like it, I think we'll do it, @georgematheos

**Comment by georgematheos** [comment]
Note that this currently does work, but it's a bit clunky:
```python
f.contramap(
    lambda original_args: args_accepted_by_f
).dimap(
    pre=(lambda *original_args: original_args),
    post=(lambda original_args, ret: my_fn_of(original_args, ret))
)
```
