### ISSUE TITLE
Syntactical sugar for builtin DSL

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#197]
Following @ztangent suggestions from my last research prez, what do we think about this sugar for syntax (also following pygen):

```python
@genjax.gen
def model():
    x_mu = TFPUniform(-3.0, 3.0) @ "x_mu"
    a = TFPUniform(-4.0, 4.0) @ "a"
    b = TFPUniform(-3.0, 3.0) @ "b"
    x = sample_x(x_mu, 1.0) @ "x"
    y = sample_y(x, a, b) @ "y"
    return y
```

(here, sample_x and sample_y are other generative functions)

To specify static kwargs like tensor shapes, specified as kwargs to the generative function.

```python
@genjax.gen
def model():
    x_mu = TFPUniform(-3.0, 3.0, shape=(3, )) @ "x_mu"
    return x_mu
```

Hierarchical addresses look like this:

```python
@genjax.gen
def model():
    x_mu = Normal(-3.0, 3.0) @ ("x_mu", 1)
    return b
```

Here's the new syntax in the context of surrounding JAX code, along with standard Python line truncation:

```python
@genjax.gen
def model(xs, max_degree=5):
    coefficients = (
        Map(TFPUniform, repeats=max_degree)(-3.0, 3.0) @ "alpha"
    )
    basis_degrees = jnp.arange(max_degree)
    ys = kernel(xs, coefficients, basis_degrees) @ "ys"
    return ys
```

This syntax modification is lightweight, easy to implement, and is exposed as an “opt in” interface from the builtin DSL (e.g. the modeling language which supports it).

**Comment by femtomc** [comment]
I should also say: this desugars to `trace(addr, gen_fn, **kwargs)(*args)` -- they are strictly equivalent under JAX's tracing.

**Comment by ztangent** [comment]
This looks great IMO!

The one edge case I can think of that I would check is when `@` is used as regular matrix multiplication. e.g.:

```python
v = jnp.transpose(jnp.ones(3))
x = MvNormal(jnp.zeros((3, 3)), jnp.identity(3)) @ "x" @ v
```

The result of the above should return whatever array was sampled 

Also, if addresses are allowed to be any type, including if they are allowed to be vectors or arrays, then we should make it clear to users that `@` is no longer playing the role of matrix multiplication. That is, it should be made clear in the following example that `v` is an address:

```python
v = jnp.transpose(jnp.ones(3))
x = MvNormal(jnp.zeros((3, 3)), jnp.identity(3)) @ v
```

(The alternative interpretation people might have of the example above is that some kind of untraced randomness is going on, where you're sampling from an `MvNormal` without giving it an address, and then multiplying it by `v`.)

**Comment by femtomc** [comment]
> The one edge case I can think of that I would check is when @ is used as regular matrix multiplication. e.g.

Good point! -- I can add some test cases for syntax.

I think this is covered by how I implemented the sugar.

@ztangent Addresses are not allowed to be JAX values -- but Python strings, integers, tuples, etc are allowed.

I should perform a static address check to ensure this and throw a nice error to users -- right now the error is quite sharp.

**Comment by femtomc** [comment]
Both syntactical sugar and static address checking have been added to lib + tests. Closing as completed. We can open a new issue if there's other modifications to syntax we want to make.
