### ISSUE TITLE
[Defactor] Support `Builtin` proposers for `Vector` combinators

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#212]
Related to #210.

The key motivating question is: how can I construct a proposal which proposes to individual indices for a vector-shaped choice map when the representation is struct-of-arrays?

**Design problem**

A bit of history: I implemented a `VectorChoiceMap` for Map and Unfold in GenJAX — but the implementation differs from Gen.jl — in Gen.jl, where we have a `PersistentVector{Trace}` — whose repr is array of structs — in GenJAX, we have just have a `Trace` whose leaves are arrays and the `VectorChoiceMap` holds an index array which marks the index of each element in the leaf arrays

Another way to think about this is that Map and Unfold take a generative function whose trace has leaf choice values of type `T[]` and transforms it into a generative function whose trace has leaf choice values of type `T[unfold_length, ]` or `T[map_length, ]`.

This is really nice from a data layout perspective (e.g. the `PersistentVector` repr is not great for SIMD stuff — that’s just because AoS is not great for SIMD stuff) — but there are subtle questions related to proposing to vector combinator choices.

For one, I think I’d really like to be able to write proposals which propose to individual indices. And, likely, it would be nice if I could write these proposals in the Builtin language — although I’m not opposed to the restriction that a user use a combinator when proposing to a combinator.

@ztangent if you remember from my last prez — I included an MH move in one of the examples which was always rejected — that’s because the current implementation requires that you pass a `VectorChoiceMap` in to update, and you can’t target individual addresses — because there is no way to control the index metadata in the `VectorChoiceMap` at the level of a proposal generative function.

**My current solution**

I really only have one solution in mind. Thinking about this solution has made me think deeper about how `Base.merge` works in Gen.jl — more on that below.

Create a specialized branch in Map/Unfold importance/update which converts a `BuiltinChoiceMap` (e.g. — think tree-shaped choice map) into a vector one. Right now, there’s only two cases which these combinators handle — `VectorChoiceMap` and `EmptyChoiceMap`. I could add a special branch for `BuiltinChoiceMap` — which adds support for a passing in `BuiltinChoiceMap` of a particular shape — e.g. ones in which the top address prefixes are integer values.

Special casing like this makes me uncomfortable. In Gen.jl, we have get_values_shallow and `get_submaps_shallow` — I think (but I’m not sure), if values become `ValueChoiceMap`, all we have is `get_submaps_shallow`. When there’s not special struct-of-array representations — I think this interface is sufficient to convert between various choice maps.

I was then thinking that instead of a specialized branch — I really just create a fallback which uses `get_submaps_shallow` — and expects the choice map provided to have top level address prefixes which are integers.

However, this raises an issue — if I expect `get_submaps_shallow` to allow me to get from `BuiltinChoiceMap` to `VectorChoiceMap`, shouldn’t I expect the reverse as well? In GenJAX — I cannot do this, because the indices created in `VectorChoiceMap` are dynamic. And, in general, the indices have “this index is not active” special values — e.g. in Unfold, when the iteration doesn’t reach up to the maximum length — the indices are filled with -1 — and those -1 indices are dynamically determined.

So — after thinking about all of this, I think the answer is that I will need to support a form of special casing.

But — it left me with more questions: how much of the conversion between choice maps is part of Gen’s interface? Is it okay if you can’t go from `VectorChoiceMap` -> tree-shaped choice map?

**Comment by femtomc** [comment]
Triage issue steps:
- [X] Separate `TrieChoiceMap` from `Builtin` and add to `genjax.core`.
- [ ] Add a new mixin -- `TrieCoerceable` -- which supports a default (but overrideable) conversion method from the choice map type to `TrieChoiceMap`.
- [ ] Consider `MapCombinator` - add code paths which try `TrieCoerceable` when a choice map is not a `VectorChoiceMap`.
- [ ] Consider `UnfoldCombinator` - (same as above).

**Comment by femtomc** [comment]
Functionality should be available via #413 -- but new triage:

- [ ] Add tests which explicitly test coercion from `BuiltinChoiceMap` to `IndexChoiceMap`

**Comment by sritchie** [comment]
Migrated to internal Notion, closing here.
