### ISSUE TITLE
[Defactor] Initial vs. final style for transformation interpreters

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#239]
JAX typically supports interpreters-as-transformers written in two styles (initial and final):

<img width="763" alt="image" src="https://user-images.githubusercontent.com/34410036/219974512-a0f8b930-23ef-468e-9053-fd43974e7caf.png">

More succinctly:

> we loosely use “initial style” to mean “build an AST and then transform it”, and we use “final style” to mean “transform as we trace.”

Most of the code that I've written is in initial style -- basically, a function is first traced to make a `Jaxpr`, and then an interpreter runs on that `Jaxpr`.

However, there may be benefits to implementing transformations in final style. The code I've written is working (which is a big plus that we should totally not misjudge) - but I'm wondering if final style:

* Improves compile/tracing times
* Improves debugging

This issue will document the answers to these questions.

**Comment by femtomc** [comment]
This morning I realized that initial style interpreters can sometimes break compositionality with final style interpreters, preventing or interfering with the effects of follow up transformations.

**Comment by femtomc** [comment]
Re - above: transformations which involve the CPS interpreter break compositionality with state (`harvest`). But the CPS interpreter can likely be re-written in final style.

edit: further investigation — I think I was wrong: likely can’t promote the CPS interpreter to final style. Instead I’m investigating why exactly the harvest pass misses some of its primitives.

**Comment by sritchie** [comment]
Closing due to "likely was wrong", re-open if we want to tackle.
