### ISSUE TITLE
[GJEP] Propose and formalize the incremental computing system

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#250]
This is quite an interesting issue — it’s the “GenJAX transformation stack” level concept which I think I’ve spent the most time passively thinking about over the last few months. There's several reasons for this:

* Incremental computing is slightly exotic, compared to e.g. forward mode with real-valued tangents.
* The system we want to support should be extensible, with both new rules and new types.

I finally think I’ve arrived at a scalable design which simultaneously integrates well with an interpreter pattern, and enables user definition of custom change types (for functions which accept custom Pytrees) and generalized JVP rules. 

But it consists of a few layers that would be almost meaningless to someone looking at this system for the first time — requiring somewhat “pro level” JAX skills to understand.

In this issue, I’ll document the design of this system (which isn’t fully implemented yet!) and attempt to describe the implementation — and how it juggles JAX concepts.

## Background

The motivating question here is how to support incremental computation in GFI implementations of `update`.

`update` has the following signature:

`update :: Trace -> ChoiceMap -> List[Change] -> Tuple[Weight, Change, ChoiceMap, Trace]`

Here, the first `ChoiceMap` is new constraints, and `List[Changes]` is a collection of new arguments - specified as "changes" to the previous arguments. The return value contains an incremental importance weight `Weight`, a return value change `Change`, a choice map containing discarded choices `ChoiceMap`, and a new `Trace`.

The interaction between Gen and incremental computing is focused on this interface method - and different generative function languages can interact / choose to incrementalize their computations in different ways.

Generally, when thinking about "incremental computing and Gen" - I've been focused on system requirements for two languages: the `Builtin` language in GenJAX, and combinators. These two languages raise different sets of requirements.

### `Builtin` requirements

The `Builtin` language requires _propagation_ of change information throughout the underlying function call / dependency graph. This is necessitated by the _means of combination_ of generative functions which the `Builtin` language exposes (e.g. writing a function).

Inside the `Builtin` language, users are also free to use other JAX code - so there's an additional layer. How do `Change` values interact with primitives? To answer this question, we must answer a related one: what computations does `update` need to perform to correctly compute its required return.

For the `Builtin` language - the `update` computation must visit all traced random choices which are affected by either (a) a change to the arguments or the dependency transitive closure or (b) a new constraint specified in the first `ChoiceMap`.

Note that there's some interesting rules here: if a changed argument propagates into a traced random choice, and has no other downstream dependents, but the random choice doesn't change - the change information ceases to propagate. If a random choice is changed by a constraint, it creates a new piece of change information ("unknown change") which propagates. When I think of formalizing the rules for this system, these are what I'm thinking about.

Generally: the right pattern to support propagation of change information is an interpreter. That's basically the hammer we have available to us in JAX, and we can (conveniently) reshape the hammer to propagate information.

**The `cache` primitive**

The `Builtin` language features a new construct - called `cache`, which supports user-directed caching of deterministic computations. This stores the result of deterministic computations in the `Builtin` trace. During `update`, `cache` attempts to determine if it needs to re-compute its return value.

The intent behind `cache` is motivated by [Giarrusso et al, 2019](https://link.springer.com/chapter/10.1007/978-3-030-17184-1_20). In "cache transfer style", we pass out stored values in the trace _which are addressed_. When we visit a `cache` site in `update`, we can choose how to process the stored value according to custom (generalized) JVP rules (see **Change propagation with `Contextual` tracers** below).

To support **extension** of the incremental computing system, `cache` + user-defined generalized JVP rules is a good place to start. I'm not yet sure if this covers all use cases we intend for incremental computing, but it at least covers custom incremental rules for deterministic functions.

### `Combinator` requirements

Combinators can selectively choose how to interact with the incremental computing system. Combinators are often structured in a particular way, so their `update` implementations can choose to arrange the computation into a more efficient form - combinators can also defer incremental computing to a generative function callee's interaction with the incremental computing system.

Combinators can internally use the incremental diff information to affect the code generation pattern which they implement for `update`.

## JAX integration

All of this boils down to a set of interesting design problems, centered around interpreters and rule propagation of "change" (or diff) values. Below, I'll try and give some context for the new interpreter design I've generated.

### Background on `Contextual` interpreter

[C.f. the interpreter README](https://github.com/probcomp/genjax/tree/main/src/genjax/_src/core/interpreters)

Recently, I discovered that adding learnable parameters to generative functions via an external (Oryx-based) implementation of state does not compose with the standard “here’s how you implement an interpreter” idiom recommended by JAX developers which I've been using in GenJAX since the first prototype.

To solve this composition problem, I had to dig deep and explore JAX’s core, and how JAX itself manages and implements its stack of interpreters. This lead me to explore the full scope of JAX interpreters in #239 and #236, as well as in #227 by studying Oryx.

The result of this search is a new type of interpreter, which I'm calling a "contextual" interpreter -- inspired by Oryx's `harvest` interpreter, but altered to fix some design issues I discovered with `harvest` (not really design issues - more like assumed optimizations by JAX, which don't always hold true).

This interpreter overloads the interface defined for JAX's core interpreters (meaning: the associated `Trace` and `Tracer` datatypes) - so it gets its own `Tracer` type (called `ContextualTracer`). In truth, if you define your interpreter by making custom overloads of these types - you're not really doing anything special (other than using a sort of advanced design pattern for interpreters). The trick with the contextual interpreter is that _it also stages out the function you're trying to transform_ - and then runs a forward `bind` interpreter over it, while passing in the custom `ContextualTrace`. 

JAX is all about data-dependence (inspired by AD), so the issue that I found in #237 (and in #239) with composition was that interpreters that handle a subset of primitives will sometimes _elide the handling of other primitives_ which may be targets for other transformations.

With this new interpreter, I fixed this problem - but I also introduced a point of overload: to use this interpreter to customize the handling of primitives, you overload a type called `Context`. This type tells the interpreter how to handle any primitives that it sees as it is propagating `ContextualTracers`, etc. So, to implement things like the GFI for the `Builtin` language - I implement contexts which overload `trace`, etc.

Now, the `Context` type deals with "in this transformation using the contextual interpreter, how do I handle this primitive" -- but I also introduced a new interface for change propagation - the `ContextualTracer` type itself. The tracer can carry metadata -- including things like "this value has changed, this value has not changed".

### Change propagation with `Contextual` tracers

Here's the data format of `ContextualTracer`:

```python
class ContextualTracer(jc.Tracer):
    """A `ContextualTracer` just encapsulates a single value."""

    def __init__(self, trace: "ContextualTrace", val: Value, meta=None):
        self._trace = trace
        self.val = val
        self.meta = meta
```

E.g. it follows the same pattern as a tracer for forward mode AD, with a `meta` slot for metadata.

The core `transform` function for the contextual interpreter looks like the following:

```python
def transform(f, ctx: Context):
    # Runs the interpreter.
    def _run_interpreter(main, *args, **kwargs):
        with Interpreter.new() as interpreter:
            return interpreter(main, f, *args, **kwargs)

    # Propagates tracer values through running the interpreter.
    @functools.wraps(f)
    def wrapped(args, metadata, **kwargs):
        with jc.new_main(ContextualTrace) as main:
            fun = lu.wrap_init(functools.partial(_run_interpreter, main), kwargs)
            flat_args, in_tree = jtu.tree_flatten(args)
            flat_fun, out_tree = api_util.flatten_fun_nokwargs(fun, in_tree)
            flat_fun = _transform(flat_fun, main, ctx)
            out_flat, ctx_statefuls = flat_fun.call_wrapped(flat_args)
            del main
        return jtu.tree_unflatten(out_tree(), out_flat), ctx_statefuls

    return wrapped
```

Users are allowed to provide an inheritor of `Context` to customize how primitives are handled, and to store extra stateful values (e.g. to handle `trace` primitives). The transformed function which comes out accepts an `args` slot and a `metadata` slot - `metadata` is how I intend to interact with the incremental computing system.

One thing which I think is important is that change values can be "smaller" than argument `Pytree` values (e.g. I could pass in a full `Pytree`, but tag it with `NoChange` - a value indicating that this argument hasn't changed) so this system must deviate from a forward mode AD system - where the input primals and tangents must have exactly the same data shape.

This motivates formalizing the types of values which can be passed into the `metadata` slot. E.g. something like the following:

```python
@dataclasses.dataclass
class Tag(Pytree):
    @abc.abstractmethod
    def should_flatten(self):
        pass

    @abc.abstractmethod
    @classmethod
    def lift(cls, value: Value) -> "Tag":
        pass
```

So metadata tags can be `Pytree` instances -- and support extension. (Side non sequitor: note how similar this is to Cassette.jl's "contextual tagging" of values - but this system should be fast, and have zero runtime overhead).

The method `should_flatten` indicates whether the inheritor should be treated as a composite value indicated some chunk change, or if it should be broken down. If `should_flatten()` returns `False`, when we flatten the arguments to `ContextualTracers(...)` - each argument will get the entire structure as a tag. Otherwise, the system will check to see if the `Pytree` for the argument which the `Tag` corresponds to matches the `Tag` `Pytree` structure.

**(Rule system) Small example**

Okay, so we have a method to tag tracers. The other thing we need is a rule system -- taking a cue from forward AD, we can define a registry. Let's think about two tag types (`UnknownChange` and `NoChange`, indicating what they say):

```python
tag_jvp_rules = {}

def tag_add_jvp(primals, tangents):
  (x, y), (x_dot, y_dot) = primals, tangents
  return [x + y], widen(tangents)
tag_jvp_rules[add_p] = tag_add_jvp
```

Here, `widen` is a lattice function - it takes in values of `Tag` type and returns values of `Tag` type. By the name, the point is that we are assuming a type of order structure on lattice elements - so e.g. `widen` might encode that, if any of the tangent tags are `UnknownChange`, we should return `UnknownChange` tag values.

However, from this basic interface - we could imagine constructing a better registry representation - including computing the "widest tag", and doing a lookup using that (so the registry becomes indexed by tag type).

**Comment by femtomc** [comment]
## Incremental computing for combinators

While the system above is primarily focused on the `Builtin` language, the combinator interaction requires some thought as well. Despite the fact that I've been focused on _JAX tracing_ above - when inside an `update` call to a combinator, the combinator will see `Diff` values - so there's no technical complexity (or, at least, I've handled conversion outside of the interface, inside the caller).

Unlike Gen.jl, where we can implement control flow which reflects on the change value (e.g. `IntChange(5)`) -- in GenJAX, the value will likely be a traced value e.g. `IntChange(Traced<...>)` which means _we can't reflect on it at compile time_.

This changes the implementation pattern, we have to be more general than Gen.jl can afford to be.

TODO: McCoy, more on this.

**Comment by sritchie** [comment]
Migrated to internal Notion.
