### ISSUE TITLE
[GJEP] `Pytree` interpreter for grammar-based generative processes

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#278]
## Background

An implementation of a `Recurse` combinator has been in the back of the mind for many months now. In another issue #234, I made some notes concerning the tension between static/dynamic dimensions in the context of `Gen.jl`'s implementation of `Recurse`.

In this issue, I want to sketch out one possible implementation strategy based upon a lower-level set of data-processing primitives.

### Grammar characteristics

One of the key characteristics of a grammar is the ability to generate tree-like structure. Tree-like structure doesn't go well with JAX - JAX likes rectangles. On the other hand, JAX does support switching and branches.

Here's what I have in mind -- start with an inductive tree-like data structure:

```
G := A | B | C | Op1 G G | Op2 G G
```

Now, I've added two operations to this inductive definition `Op1` and `Op2` - generating an expression from this grammar involves selecting a term - if the term contains `G`, it's non-terminal, recursively select for that `G`.

For example, imagine an inductive definition for addition and multiplication over natural numbers:

```
G := Nat | (+) G G | (*) G G
```

Next, we want an interpreter to give meaning to terms. To define an interpreter, we must define an object language - the language of values which the interpreter can return. For the addition interpreter above, that's `Nat`. How would we implement the interpreter in a language which supports recursion? We'd implement it with recursion.

```
eval :: G -> Nat
eval (+ G G) = +_prim (eval G) (eval G)
eval (* G G) = *_prim (eval G) (eval G)
```

(this is rough nomenclature - but hopefully if you're familiar with `eval` interpreters from elsewhere, you'll get the gist).

JAX doesn't support unbounded recursion _at runtime_ across changing data types (e.g. you'd implement recursion via `while`, but `while` has strict requirements on data going in and out) -- _but you can use recursion at compile time_.

As long as the compile-time recursion terminates in Python, JAX can generate code. So e.g. to access this, you'd provide a specific term e.g. `T = +_prim (*_prim 2 2) 2` - this would correspond at compile time to a representation of the inductive data type whose type-level values you can reflect on and use to inform JAX what code paths it should trace.

The problem here is that JAX will only generate code _for this specific term_ - you can't use the resulting `jax_eval` for other terms `T in G`.

To remedy this, you need to push the code generation choices from some of things which you reflected on at the type-level _to runtime_ - which means we need to use `cond` (branches). Additionally, the information about types which we might use at compile time to decide what code to trace -- now needs to be pushed to runtime as well -- which means assigning each term in the inductive definition a natural number index.

```
Nat -> 0
(+) -> 1
(*)  -> 2
```

Now, where do we put the recursive references to `G` for `(+)` and `(*)` - the right thing to do here is to define an array representation for each term and then construct a `while` loop to process the representation using the semantics of a stack machine - starting from the leaves.

```
Nat -> (0, value)
(+) -> (1, 0)
(*) -> (2, 0)
```

Now, any tree in our addition grammar can be flattened into a `2 x ~N` (save analysis on size of N vs. original tree depth for later).

For example, `T = +_prim (*_prim 2 2) 2` (isomorphic to `2 x N` array) -- ordered in a leftmost traversal:

```
(0, 2)
(0, 2)
(2, 0)
(0, 2)
(1, 0)
```

To interpret this representation, we pass the representation into a `while` loop with an initialized stack (say, conservatively, whose length is equal to the size of our expression -- we can likely analyze the grammar structure and guess what this should be?)

### Taking a step back

But notice what we've done here! We've provided a way to write an interpreter on grammar expressions which can switch at runtime - allowing us to interpret any fixed term `T` - with the caveat that we need to translate `T` into an array representation which faithfully represents the original tree under interpretation.

But we can write that transformation separately. For each operation, we can provide an implementation of that operation, which we switch on in the stack execution semantics.

Above, our machine -- when seeing a `1` in the first index, while use the addition implementation (for example).

**Comment by sritchie** [comment]
Migrated to internal Notion.
