### ISSUE TITLE
[Docs] Document coryx rules

### ISSUE THREAD

**Issue by Joaoloula** [genjax-community/genjax#289]
Write documentation specifying which kinds of operations preserve ildj compatibility for coryx

**Comment by femtomc** [comment]
Thanks @Joaoloula! This is a great idea.

There are other language rules to document as well, dealing with the inversion process. Like the arity of the return value (a single value has arity = 1) must match the number of random choices to allow for the possibility of inversion.

I have an idea about how to setup documentation for “language layers” like this one, that I can sketch out. If you want to use Coryx for your work we can then discuss the best way to do the documentation.
