### ISSUE TITLE
[BUG] `genjax.Map` does not support Pytree `in_axes`

### ISSUE THREAD

**Issue by midfield** [genjax-community/genjax#399]
**Describe the bug**
Contrary to expectations around e.g. `vmap`, you cannot pass in Pytree prefixes for `in_axes` to `genjax.Map`.

**To Reproduce**
```
@genjax.gen
def foo(y, args):
  loc, scale = args
  x = genjax.normal(loc, scale) @ 'x'
  return x + y

_, trace = genjax.simulate(genjax.Map(foo, in_axes=(None, (0, None))))(key, (10., (jnp.arange(3.), 1.)))
```

**Expected behavior**
Should vectorize over the `loc` argument, but instead gives an error.

**Additional context**
See `jax._src.api._mapped_axis_size` maybe?

**Comment by midfield** [comment]
from flax

```
  def inner(scope_fn, repack_fn, variable_groups, rng_groups, *args):
    def find_axis_size(axis, x):
      if axis is not None:
        leaves = jax.tree_util.tree_leaves(x)
        if leaves:
          return leaves[0].shape[axis]
      return ()

    # split rngs
    axis_sizes = jax.tree_util.tree_map(find_axis_size,
                                        (variable_in_axes, in_axes),
                                        (variable_groups, args))
 ```

**Comment by femtomc** [comment]
This is interesting — because I basically just forward in_axes to vmap. I’ll take a look.

**Comment by midfield** [comment]
You have a function which tries to determine what the batch size is by inspecting `in_axes` and `args`, but it assumes that `args` is just a tuple and not a pytree nest.  I'll submit a PR shortly.

@derifatives
