### ISSUE TITLE
[BUG] Converting closures to Pytrees by default seems to introduce many problems

### ISSUE THREAD

**Issue by midfield** [genjax-community/genjax#402]
**Describe the bug**
This is not really a specific bug, sort of a design refactor.

Closures are converted to Pytrees by default.  There have been a number of issues (#387 ?) related to this.

**To Reproduce**
The "constructor pattern" is commonly used in JAX:

```
def make_foo(static_args):
    @genjax.gen
    def foo(dynamic_args):
        ...
```

**Comment by femtomc** [comment]
Closing as complete via #403.
