### ISSUE TITLE
[Defactor] GenJAX's testing strategy

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#420]
I'm opening this issue to discuss / document approaches to testing code from GenJAX.

As of this day, we've had quite a haphazard approach to testing -- (basically, tests included at the whim of the maintainer). But now, several people are relying on the system - and it's important to take a serious approach to testing.

There roughly 4 levels of unit tests:

* "Core" functionality, and basic generative functions (e.g. Distributions, and the Builtin language)
* "Combinator" functionality -- e.g. the associated data types and interfaces for combinators -- which themselves rely upon the "Core" functionality
* "Inference" functionality -- e.g. the inference standard library -- which typically rely on just the generative function interface, and may be called with any type of generative function.

Finally, the 4th category is "Misc" -- e.g. extension languages (like ADEV, or GenSP) which I'd roughly treat like inference (they typically assume the generative function abstraction, and may call the interfaces for any generative function, and potentially work with their data types).

An honest assessment:

* The "Core" testing is probably half of where it needs to be. There's unit tests for the interfaces in the `Builtin` language. The `Distributions` functionality relies on the correctness of other libraries -- but there are essentially no tests for distributions. There's boiler plate tests which we could fill in for the interfaces for `Distributions` (quickly, probably in ~2 hours).
* The "Combinator" testing is paltry. It was very bad ~2 weeks ago, now it's slightly less bad. There's some simple tests for all the combinators, but it's not close to the level of "Core" (and remember, "Core" also needs work).
* Inference testing is non-existent -- modulo the SMC tests I just put in with #413. Inference has two styles of test:
    * Smoke test: make sure a piece of code can actually run, with applicable generative functions.
    * Correctness test: make sure the estimates returned by inference have the expected behavior in a large N limit (e.g. data marginal estimates for IS / SMC).

Let's start working on this issue now, over the next few weeks. Eventually, we might get enough person power to fill in tests for the library outside of the collaboration.

@csuter @midfield

**Comment by sritchie** [comment]
Migrated to internal Notion.
