### ISSUE TITLE
[BUG] Can't update the index of Switch traces

### ISSUE THREAD

**Issue by brianwa84** [genjax-community/genjax#427]
**Describe the bug**
I'd like to update the argument passed to a Switch genfn.

**To Reproduce**
```
@genjax.gen
def regular():
    x = genjax.normal(0, 1) @ 'x'
    return x

@genjax.gen
def outlier():
    x = genjax.normal(0, 10) @ 'x'
    return x

model = genjax.Switch(regular, outlier)
_, tr = model.simulate(jr.PRNGKey(0), (0,))

tr.update(jr.PRNGKey(1), genjax.EmptyChoiceMap(), (genjax.diff(1, genjax.UnknownChange),))
```

**Expected behavior**
Gives weight and updated trace.

**Actual**
The trace has an empty 'args' tuple, perhaps because it has stashed the 'index' into SwitchChoiceMap.index, but it still insists on receiving a diff for the index arg which suggests argdiffs is the right way (feels like the right way, esp as no SwitchChoiceMap exists in the API). 

I hoped that embedding the switch into a larger genfn might help, but still get an error:
```
@genjax.gen
def q(ix):
    y = model(ix) @ 'y'
    return y
_, tr = q.simulate(jr.PRNGKey(0), (0,))

tr.update(jr.PRNGKey(1), genjax.EmptyChoiceMap(), (genjax.diff(1, genjax.UnknownChange),))
```

In both cases, the exception is a deeply nested `ValueError: safe_map() argument 2 is longer than argument 1`

**Execution environment (please complete the following information):**
 - OS: [e.g. iOS] linux gcp
 - Python version: [e.g 3.10] '3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]'
 - GenJAX version: [e.g. 22] e72503e47f6f7e4a8dff9eae9520d4c4985cba87 ../submodules/genjax (e72503e4)

**Comment by brianwa84** [comment]
Another couple things I tried:
```
tr.update(jr.PRNGKey(1),
          tr.chm.new(index=1, submaps=[genjax.EmptyChoiceMap()] * 2), 
          (genjax.diff(1, genjax.UnknownChange),))
```
==> `TypeError: tree_map() missing 1 required positional argument: 'tree'` (wants non-empty submaps)

```
tr.update(jr.PRNGKey(1),
          tr.chm.new(index=1, submaps=tr.chm.submaps), 
          (genjax.diff(1, genjax.UnknownChange),))
```
==> `Exception: Both tries have a leaf at x.`

**Comment by femtomc** [comment]
thanks! I'll take a look

**Comment by derifatives** [comment]
The issue is that the `BooleanMask` applyed in `_update`, is making `update` on the branch functions barf.

A simple example that exposes the issue:
```
@genjax.gen
def simple_normal():
    y1 = genjax.trace("y1", genjax.normal)(0.0, 1.0)
    y2 = genjax.trace("y2", genjax.normal)(0.0, 1.0)

@genjax.gen
def simple_bernoulli():
    y3 = genjax.trace("y3", genjax.bernoulli)(0.3)

switch = genjax.SwitchCombinator([simple_normal, simple_bernoulli])

key = jax.random.PRNGKey(17)
key, tr = switch.simulate(key, (0,))
                                                                                                                                                                                        
submap = tr.get_choices().submaps[0]
# This would work:
# key, tr = simple_normal.update(key, submap, genjax.empty_choice_map(), ())

submap = BooleanMask.new(True, submap)
# This barfs:
key, tr = simple_normal.update(key, submap, genjax.empty_choice_map(), ())
```

**Comment by femtomc** [comment]
@derifatives I think I understand the issue. If `BooleanMask` _is applied to a trace_, it currently fails to update correctly.

I think, in the implementation, I should avoid applying masks to traces (traces, should, roughly -- "always be valid" -- and anything which deals with selecting which valid trace to return (for e.g. the switching semantics) should be handled by the implementation of `update`, before returning a valid trace.

Expecting `Distribution` generative functions (a "leaf" generative function type, currently the only one which dispatches with `BooleanMask`'d data at the leaves) to also somehow handle masked traces seems like it will increase the complexity of `Distribution`'s update implementation.

**Comment by sritchie** [comment]
Here's the start of a repro in modern genjax:

```python
import genjax
import jax

@genjax.gen
def simple_normal():
    _y1 = genjax.normal(0.0, 1.0) @ "y1"
    _y2 = genjax.normal(0.0, 1.0) @ "y2"

@genjax.gen
def simple_bernoulli():
    y3 = genjax.bernoulli(0.3) @ "y3"

switch = genjax.switch(simple_normal, simple_bernoulli)

key = jax.random.PRNGKey(17)
tr = switch.simulate(key, (0, (), ()))
                                                                                                                                                                                        
submap = tr.get_choices().c1
```

@femtomc I think fixed this, based on the linked commits. Please open again if you run into this.
