### ISSUE TITLE
[BUG] genjax.normal.logpdf gives incorrect answers for std 

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#430]
**Describe the bug**
genjax.normal.logpdf gives incorrect answers for std != 1

**To Reproduce**
Steps or code (or Gist!) to reproduce the behavior:
`genjax.normal.logpdf(-0.8245, 0., 10.)`   # ==> Array(6.0963836, dtype=float32)

**Expected behavior**
`genjax.normal.logpdf(-0.8245, 0., 10.)`   # ==> Array(-3.2249227, dtype=float32)

**Additional context**
The logpdf is computed using:
`            -1.0 * (jnp.square(jnp.abs(z)) + jnp.log(2.0 * pi)) / (2 - jnp.log(std))`

This is misparenthsized. A correct expression would be:
`            (-1.0 / 2) * (jnp.square(jnp.abs(z)) + jnp.log(2.0 * pi)) - jnp.log(std)`

It is fortuitously correct when std=1, becuase jnp.log(1) = 0.

This is easy to point fix, but it's probably worth discussing an overall strategy around distributions. I'm wondering if it's plausible to just wrap TFP's base distributions, which have had a *lot* of work put into testing and numerical correctness.

**Comment by femtomc** [comment]
@derifatives I'm fine with exposing TFD -- instead of `scipy` (as "the default") -- but should we also file a bug upstream?

**Comment by femtomc** [comment]
Closed on nightly @ https://github.com/probcomp/genjax/commit/c827133c497918f508e5e2222547efcea13d307d. Will keep open until hits main.

**Comment by sritchie** [comment]
Closing since this is fixed in nightly. We'll be releasing a new version tomorrow, @derifatives .
