### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#431]
**Describe the bug**
Cannot access element of SwitchTrace after vmap'd simulate.

**To Reproduce**
```
@genjax.gen
def f1():
    return genjax.tfp_normal(0., 1.) @ 'y'

@genjax.gen
def f2():
    return genjax.tfp_normal(0., 2.) @ 'y'

s = genjax.SwitchCombinator([f1, f2])

s_keys = jax.random.split(jax.random.PRNGKey(17), 3)
# (Just select 0 in all branches for simplicity:)
_, tr = jax.vmap(s.simulate, in_axes=(0, None))(s_keys, (0,))
tr["y"]
```

Eventual error is `TypeError: eq got incompatible shapes for broadcasting: (2,), (18,).`,  triggering at TypeError: eq got incompatible shapes for broadcasting: (2,), (18,).

**Expected behavior**
Should return a tensor.

**Comment by femtomc** [comment]
Investigating this.

**Comment by femtomc** [comment]
Should be fixed at https://github.com/probcomp/genjax/commit/69d312ecb8759d4d3d21e743b9fdbf12ba311ffb.

(ignore jupyter, I really need to remove VC tracking for that binary)
