### ISSUE TITLE
[Docs] The method `genjax.index_choice_map` takes list of integers not single integer

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#455]
The docstring of `genjax.index_choice_map` states:

![image](https://uploads.linear.app/01eb02c3-97fe-4268-bdb2-c6d2bb5518eb/3bbda458-9516-4d93-b2b8-b876114e7a68/7b4c5679-7e87-4d8e-a684-2e4faae8853a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAxZWIwMmMzLTk3ZmUtNDI2OC1iZGIyLWM2ZDJiYjU1MThlYi8zYmJkYTQ1OC05NTE2LTRkOTMtYjJiOC1iODc2MTE0ZTdhNjgvN2I0YzU2NzktN2U4Ny00ZDhlLWE2ODQtMmU0ZmFhZTg4NTNhIiwiaWF0IjoxNzE2MjM3NTE0LCJleHAiOjMzMjg2Nzk3NTE0fQ.PiJcBMC5GTwgDPHmzPoMUMKRqBIAEFrzetqxSe2joS0)

But we get:

![image](https://uploads.linear.app/01eb02c3-97fe-4268-bdb2-c6d2bb5518eb/e8e9aac9-aa18-4173-9ef1-2fa6930b3a6f/34e1560d-e09c-4947-8e4d-01d283dd4d92?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAxZWIwMmMzLTk3ZmUtNDI2OC1iZGIyLWM2ZDJiYjU1MThlYi9lOGU5YWFjOS1hYTE4LTQxNzMtOWVmMS0yZmE2OTMwYjNhNmYvMzRlMTU2MGQtZTA5Yy00OTQ3LThlNGQtMDFkMjgzZGQ0ZDkyIiwiaWF0IjoxNzE2MjM3NTE0LCJleHAiOjMzMjg2Nzk3NTE0fQ.1w5YKzudF6CJnqOXH5Xs-kBKH22U6YXxXjQ8Yuxlu-U)

**Comment by femtomc** [comment]
I think the right thing to do here is just to promote integers to index into the leading dimension of the data (here, your `jnp.ones(3)`). I don't have a code path for this, but I can add one.

**Comment by femtomc** [comment]
@mirkoklukas https://github.com/probcomp/genjax/pull/457

**Comment by sritchie** [comment]
@mirkoklukas , looks like this is closed as of the linked PR.
