### ISSUE TITLE
[GJEP] Method to create constraints choicemaps from a reference choicemap.

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#456]
I have a choicemap `ch` from a trace
```
└── :X
    └── (Vector)
        └── :ij
            └──  f32[200,3]
```
I can do
```
ch[("X","ij")]
```
It would be great to have a method that can create constraints from `ch` and `("X","ij")` and some `data` and makes it easier to 
get choice maps like
```
constraints = genjax.choice_map({"X": 
        genjax.vector_choice_map(
            genjax.choice_map({"ij": data })
        )
}) 
```
It should take the "reference" choicemap `ch` as an argument as well
```
create_constraints(addr=("X","ij"), data=data, reference_chm=ch)
```

**Comment by femtomc** [comment]
In the method, we'd just pass the reference choice map as the base object:

```
new_chm = ch.replace(("X", "ij"), data)
```

for instance.

**Comment by mirkoklukas** [comment]
I think `ch` it should be an argument, it might contain **more** choices than we want to "constrain" on.  And if the arg is None we could just return a nested choicemap. Think the the name `replace` suggests we just alter at that particular address, which we dont', we want to throw away the rest.

**Comment by femtomc** [comment]
I don't think we need the method in the form you describe above -- it's too specific.

To express what you just described, here's what I would do:

```
select(("X", "ij")).filter(ch).replace(("X", "ij"), data)
```

Here, `select` first filters the choice map to just the addresses you want, and then replace returns a new structure (same structure as the output of the filter) with the data replaced.

I really like this composition, because it reflects a design philosophy present [in functional optics](https://hackage.haskell.org/package/optics-0.4.2.1/docs/Optics.html).

**Comment by femtomc** [comment]
@mirkoklukas then, if you want "in-place filter and set", you'd just define it:

```
def project_replace(chm, addr, data):
     ...
```

nothing wrong with having a bit of library code, although I'm not sure if the name is quite right yet

**Comment by mirkoklukas** [comment]
But `select(...).filter` seems to forgets about vector choice maps. So one can't feed `select(("X", "ij")).filter(ch).replace(("X", "ij"), data)` to `model.importance`

**Comment by femtomc** [comment]
> But select(...).filter seems to forgets about vector choice maps. So one can't feed select(("X", "ij")).filter(ch).replace(("X", "ij"), data) to model.importance

Two things:

* I think I should fix the behavior of `HierarchicalSelection` (e.g. `select`) so that it preserves the choice map type when `filter` is applied.
* I think `.replace(..., data)` should optionally accept:
    * `data` is a scalar value, in which case it gets wrapped in a `ValueChoiceMap` and inserted
    * `data` is another choice map, in which case it gets inserted at as a branch at the indicated address.

**Comment by femtomc** [comment]
@mirkoklukas Similar to your other feature request, I've started to explore this functionality on `nightly`. We can discuss in person on Monday.

**Comment by sritchie** [comment]
@femtomc can you say more about what we want here? I don't understand the "old code" — we want something like `assoc` here in Clojure, I guess, where we can sub values into a reference choicemap?

We can do this now with `|`. I THINK that `C["X", 0, 1, "ij"].set(3.0) | chm` would cover overriding a single value. @mirkoklukas let me know if this works, and re-open if I'm missing the meaning here, please!
