### ISSUE TITLE
[BUG] renaming needed for notebooks to run

### ISSUE THREAD

**Issue by MathieuHuot** [genjax-community/genjax#471]
**Describe the bug**

These are all in notebooks.
- In Gaussian process modeling with `tinygp`, in the first box 
```
TypeError: 'LazyLoader' object is not callable
```

- In Probabilistic programming with estimated densities, in the box: 
```
key, sub_keys = genjax.slash(key, 300)
_, trs = jax.vmap(model.simulate, in_axes=(0, None))(sub_keys, ())
chm = trs.strip()
```
I get 
```
Exception: EmptyChoiceMap has no leaf value.
```

- In Implementing the builtin modeling language, I get
```
AttributeError: module 'genjax' has no attribute 'Normal'
```

- In Incremental computation for generative functions, I get
```
AttributeError: module 'genjax' has no attribute 'MCMCKernel'
```

- In Differentiable programming with GenJAX, I get
```
ImportError: cannot import name 'TFPUniform' from 'genjax' (/Users/matuot/repos/genjax/src/genjax/__init__.py)
```
and a few boxes below
```
TypeError: MapCombinator.new() got an unexpected keyword argument 'repeats'
```
and then
```
TypeError: unhashable type: 'list'
```

**Execution environment (please complete the following information):**
 - OS: MBP M2
 - Python version: 3.11
 - GenJAX version: 0.0.1

**Comment by sritchie** [comment]
The notebooks all run now. Thanks, @MathieuHuot !
