### ISSUE TITLE
[BUG] Updating a trace away then back from original changes the score

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#477]
Not sure if this is a bug. 
Does update first compute the weight and add it to the old score?

![image](https://github.com/probcomp/genjax/assets/5437585/fb49bdc3-0c8b-4557-a58a-4d4e29eed4b5)

**Comment by sritchie** [comment]
@mirkoklukas , I can't tell without the actual model in hand how to reproduce this. Open if this is still an issue!

**Comment by mirkoklukas** [comment]
@sritchie The model is irrelevant here, it's more documentation request, because it is a potential pitfall. It is about updating a trace `t` to some other trace `t'` and then back to `t`. The scores for the initial trace and the last updated one, which is the same as the initial, differ. I guess this is due to the way the updated score is computed. It's not a "bug" in that sense.

**Comment by femtomc** [comment]
that's a bug, unless the model has untraced randomness (in which in may not be a bug)

**Comment by littleredcomputer** [comment]
don't we need an inverse choicemap in the second update to undo the effect of `ch` applied to the first trace (I can see we put the args back the way they were, but what about the other values?)

**Comment by femtomc** [comment]
@mirkoklukas It's likely a bug -- but to fix it, we need a reproducible example that we can run outside of your codebase

**Comment by femtomc** [comment]
@mirkoklukas No, we don't add the weight to the previous score for the implementation of `update`  -- we compute and track the new score separately. But without further information, we can't figure out where the issue is (in what generative functions, etc).

So I suspect this is a bug, but if you want this fixed -- re-open with an example that we can run.
