### ISSUE TITLE
Cookbook example: Map operator with an additional shape argument

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#493]
Example: I want to map some function over each pixel of an image. But I don't want the result to be flattened, and rather stored as a 2D array

**Comment by mirkoklukas** [comment]
I basically want to index into the choicemap with a 2d-index (i,j) and not the flattened version.

**Comment by sritchie** [comment]
Once we merge #1072 , this will be possible with

```python
import genjax
import jax.numpy as jnp

@genjax.gen
def model(v):
    return genjax.normal(v, 1.0) @ "x"

tr = (
    model.vmap(in_axes=(0,))
         .vmap(in_axes=(0,))
         .simulate(key, (jnp.ones((50, 50)),))
)

chm = tr.get_sample()
chm[1, 2, "x"]
;; Array(1.697814, dtype=float32)
```
