### ISSUE TITLE
[Docs] @pawamoy doc thread

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#502]
@pawamoy we can discuss here:

I usually build and serve the documentation via `nox`:

```
nox -r -s docs-build
```

or 

```
nox -r -s docs-serve
```

I've placed the code which fetches `mkdocstrings` and `mkdocs-material` into the `noxfile` -- feel free to adjust to the public versions (or I can do so, on a branch -- for you to debug).

**Comment by pawamoy** [comment]
OK so I'm able to replicate the issue. On my end, it seems that the executed code blocks fail for various reasons:

- `ModuleNotFoundError: No module named 'tinygp'`
- `NotImplementedError`

...and in turns make the conversion of the docstring for Markdown to HTML fail. I suspect this goes even higher and silently makes the rendering of the whole function template fail. That's the only explanation I can think to explain why even the headings aren't rendered.

**Comment by pawamoy** [comment]
Well nope, even disabling all executed code blocks shows no members on this class :thinking:

**Comment by pawamoy** [comment]
OK, that's an issue with the template. These conditions are wrong: `{% if members_list is none and function.is_public(check_name=False) %}`.

It should be `{% if members_list is not none or function.is_public(check_name=False) %}`. Fix incoming!

**Comment by pawamoy** [comment]
Just released versions 1.5.2 and 1.5.2.1.3.0, you can close this issue :slightly_smiling_face:

**Comment by femtomc** [comment]
Thank you @pawamoy!
