### ISSUE TITLE
[Defactor] Choice map conversion and generic fallbacks

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#556]
JAX is quite rigorous about the separation between dynamic and static information, and we also want to be rigorous -- to match JAX's expectations. At the same time, we'd like to expose concise interfaces that work "in general", without too much hassle for the user.

In general, the philosophy of GenJAX is to coerce users onto optimized code paths, but allow them to deviate from these paths for expressivity -- and provide warnings (e.g. via a static logging system, if opted in) when users are taking performance hits. There is no place where this philosophy is harder tested than considering how choice map constraints are passed into interfaces like `importance` and `update` (or `assess`).

Consider the following example of a model + a proposal to be used in importance sampling (for instance):

```python
@genjax.gen(genjax.Unfold, max_length=5)
def chain(z_prev):
    z = genjax.tfp_normal(z_prev, 1.0) @ "z"
    _ = genjax.tfp_normal(z, 1.0) @ "x"
    return z

@genjax.gen
def builtin_proposer():
    z = genjax.tfp_normal(0.0, 1.0) @ (1, "z")
    return z
```

This is a perfectly normal thing that a user might write down -- `genjax.Unfold` creates an address hierarchy like `(1, "z"), (2, "z"), ... (1, "x"), (2, "x"), ...` (up to index 5) -- and the user wants to target a particular index via a proposal. Here, the index is *static*. 

In the past, the way we handled this code path was via a special method defined on `IndexedChoiceMap` called `convert` -- which would be called on the choice map produced by the proposal before invoking specialized `UnfoldCombinator.importance` implementations. An `IndexedChoiceMap` is a choice map whose internal representation is designed to support tagging homogeneous (struct-of-array) choice maps with index information (e.g. it explicitly represents the hierarchy `(1, "z"), ...` by representing the indices as an array).

If a user attempted to use a proposal of the following form (which is invalid for the the address hierarchy exposed by `UnfoldCombinator` using the above kernel), we would error:

```python
@genjax.gen
def builtin_proposer():
    z = genjax.tfp_normal(0.0, 1.0) @ (1, "z")
    return z
```

This behavior is appropriate, and reflects Gen's semantics. However, let's modify our proposal in one other way:

```python
@genjax.gen
def builtin_proposer(t, ):
    z = genjax.tfp_normal(0.0, 1.0) @ (t, "z")
    return z
```

Now, the `t` argument affects the address hierarchy exposed by the proposal -- and `t` is *dynamic*. This is the crux of a large number of design patterns in custom proposal SMC. We'd like to expose automated SMC, but we want our implementation of SMC to be generic across the GFI. This explicitly puts tension on the separation between *static* and *dynamic* choice map representations -- because e.g. now, in `UnfoldCombinator.update` (along with the aforementioned `UnfoldCombinator.importance`), we must try a type of conversion between choice maps.

Furthermore, the choice maps produced by the above proposal _are already dynamic_ - because the static `HierarchicalChoiceMap` (which uses a meta-language `Trie` at JAX tracing time to represent the address hierarchy) cannot utilize dynamic addresses.

My discussion above is designed to expose a sort of tension which I think we can resolve with a good design choice now. 

One more thing I'll add: currently, _we're actually leaving optimized code on the table_ in the case where the proposal with fully static addresses is used:

```python
@genjax.gen
def builtin_proposer():
    z = genjax.tfp_normal(0.0, 1.0) @ (1, "z")
    return z
```

A `HierarchicalChoiceMap` of this form is fully static, and contains a static representation of the indices. But to coerce this onto code paths which work for `UnfoldCombinator`, we actually currently eliminate some of the static information when we convert to `IndexedChoiceMap`. We could write code which analyzes the the static address set _at JAX tracing time_ and generates an optimized `update` implementation (for instance).

## What interfaces are affected by this tension?

The key choice map interfaces which are affected by this tension are `get_subtree` and `has_subtree`. 

`get_subtree` always returns a choice map, but the information passed into the interface (an address -- which may be a static string, or a dynamic integer array, or an n-tuple of either) may be dynamic/static -- and the implementation and "universe level" (universe 1 = static, universe 0 = dynamic) depends on the information.

similarly, `has_subtree` always returns a `Bool`, but it may return a static `Bool`, or a dynamic one -- depending again on whether the address passed in is static or dynamic, or the choice map itself has static/dynamic structure.

**Comment by sritchie** [comment]
Migrated to internal Notion.
