### ISSUE TITLE
[BUG] Irrelevant choice map values are silently ignored.

### ISSUE THREAD

**Issue by derifatives** [genjax-community/genjax#631]
On the dynamic addresses branch:
```
_phi, _q, _beta, _r = (0.9, 1., 0.5, 1.)
@genjax.gen
def next_step(state):
    (x_prev, z_prev) = state
    x = genjax.normal(_phi * x_prev, _q) @ 'x'
    z = _beta * z_prev + x
    y = genjax.normal(z, _r) @ 'y'
    
    return (x, z)
genjax.importance(next_step)(jax.random.PRNGKey(3), genjax.choice_map({'fff': 3.}), ((0., 0.),))[1].get_score()
# Array(-2.3489804, dtype=float32)
genjax.importance(next_step)(jax.random.PRNGKey(3), genjax.choice_map({}), ((0., 0.),))[1].get_score()
# Array(-2.3489804, dtype=float32)
```

**Comment by sritchie** [comment]
We'll keep this open, as we definitely want to error if someone provides irrelevant addresses.

**Comment by sritchie** [comment]
[GEN-418](https://linear.app/chi-fro/issue/GEN-418/can-genjax-validate-the-structure-of-a-choicemap-consumed-by) has good discussion on this. I've marked it as a duplicate of this issue.

**Comment by MathieuHuot** [comment]
@sam just want to flag that this probably should be part of the push on "making choice map nice". But you decide whether it's for this cycle or a future one.
