### ISSUE TITLE
[BUG] Unexpected tracer leak instantiating a TFPDistribution

### ISSUE THREAD

**Issue by midfield** [genjax-community/genjax#654]
**Describe the bug**
Trying to instantiate a TFP distribution inside of a generative function results in a tracer leak.

Notes:
1. TFP distributions can take tracers in their constructors just fine:
```python
import jax
import jax.numpy as jnp
import jax.random as jr
from tensorflow_probability.substrates import jax as tfp

tfd = tfp.distributions

@jax.jit
def foo(key):
  k1, k2 = jr.split(key, 2)
  probs = jr.dirichlet(k1, jnp.ones(2))
  dist = tfd.Categorical(probs=probs)
  return dist.sample(seed=k2)

foo(jr.PRNGKey(0))
```
2. I'm not sure that TFP distributions have anything to do with this, it seems like a generic tracer leak issue.

**To Reproduce**

```python
import jax
import jax.numpy as jnp
import jax.random as jr
from tensorflow_probability.substrates import jax as tfp
import genjax

tfd = tfp.distributions

@genjax.gen
def foo():
   probs = genjax.dirichlet(jnp.ones(2)) @ 'probs'
   dist = tfd.Categorical(probs=probs)
   gdist = genjax._src.generative_functions.distributions.tensorflow_probability.TFPDistribution(lambda: dist)
   rval = gdist() @ 'rval'
   return rval

with jax.checking_leaks():
  foo.simulate(jr.PRNGKey(0), ())
```

**Expected behavior**
Should run without an error.

**Screenshots**
N/A

**Execution environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.11
 - GenJAX version: nightly

**Additional context**

**Comment by femtomc** [comment]
@midfield The issue here is that `dist` is storing the tracer, which goes into a lambda, which is then stored inside a _static field_ in `genjax.TFPDistribution`, which is then stored in the trace and attempted to be returned out of JAX tracing code -- hence the issue.

**Comment by femtomc** [comment]
@midfield I believe there's a relatively simple fix, which will also allow users to customize how their TFD distributions are constructed.

The fix is to use the `lambda *args : dist(*args)` _as the default static field_ inside a `TFPDistribution`. You can then construct these objects custom, as you're doing -- but then your code will be a "mistake" -- because you should provide the lambda, and also invoke the distribution with the arguments (then, the arguments -- which are traced values -- won't be closed over, but just used to construct a `tfd` distribution for sampling / logpdf.

**Comment by midfield** [comment]
I think I have another version of this which does not involve TFPDistribution at all.

This doesn't work:

```
def log_binomial_coefficient(x, y):
  return -jnp.log(x + 1) - jsp.special.betaln(y + 1, x - y + 1)

class RandomChoice(genjax.distributions.ExactDensity):
  def sample(self, key, range_, shape):
    return jr.choice(key, range_, shape, replace=False)

  def logpdf(self, value, range_, shape):
    count = np.prod(shape)
    return -log_binomial_coefficient(range_, count)
```

because `jr.choice` needs `shape` to be static, but `genjax` traces it.  If I try to lift the `shape` to an instance variable, I get some weirdness when I try to use it in a genfn.

If I try to lift both arguments to constructors, instantiate the class outside the genfn and use it inside, I get

```
TypeError: RandomChoice.__init__() missing 1 required positional argument: 'range_'
```

If I lift only the shape argument, I get the same tracer error as before.

**Comment by midfield** [comment]
This is the solution I came to

```
def make_random_chooser(range_, shape):
  class RandomChoice_(genjax.distributions.ExactDensity):
    def sample(self, key):
      return jr.choice(key, range_, shape, replace=False)

    def logpdf(self, value):
      count = np.prod(shape)
      return -log_binomial_coefficient(range_, count) 
  return RandomChoice_
```

**Comment by femtomc** [comment]
@midfield There's a solution to this via `Pytree` in GenJAX, but it's not on `nightly` yet -- but will be in the next big PR.

Roughly, now one can pass static arguments into interfaces which use tracing via `Pytree.const(your_literal)`.

It doesn't fix the underlying usability concern (that it's tough to understand when and why transformations are occurring), but it might slightly alleviate this pain point.

**Comment by midfield** [comment]
says @femtomc 

Right -- two things:

Thing one -- there's a new idiom which allows you to pass static literals as arguments, by abusing Pytree. It's quite a simple fix, but should work.

Thing two -- the above fix doesn't solve the usability problem of "when will my arguments be traced".

This is a big problem, but it's not clear to me how to handle it effectively. One thing would be to try a design for the StaticGenerativeFunction language which just uses Python-like effect handlers -- instead of, usinf jax.make_jaxpr + interpreters to give semantics to code.

The problem is that Python-like effect handlers are insufficient to implement the update interface -- which does require JAX tracing to effectively perform incremental computation.

So one thing would be to mix these two approaches -- but I'm concerned this could lead to real confusion -- why is my static thing working for simulate, but not for update?

Also @midfield  -- you should be able to fix this by defining shape as a static parameter to RandomChoice (the class) to instance -- so I'm a little confused why that didn't work

Can you say a little more about "rerun the constructor when i use it inside of a genfn"

You'll have to invoke it in a funky way:your_dist = RandomChoice(shape=(3, 3))
your_dist(value, range) @ "addr"

but since RandomChoice is a Pytree, nothing weird should be going on.

**Comment by midfield** [comment]
I don't want to have a static class argument, that would mean having a separate class per sample shape, although that's effectively what I'm doing now with the constructor function.  

When I use a instance argument, it seems to want to re-run the constructor.  It is possible this is an old bug since we are not using a very recent GenJAX, so maybe not worth debugging for now.

What is the idiom for passing static literals as arguments?

**Comment by femtomc** [comment]
If you send me the commit you're on I can see if the idiom is available, otherwise I can show you the idiom directly.

**Comment by midfield** [comment]
33031c35d6c6a165b7146bafc9feecc117e06b38

**Comment by sritchie** [comment]
See #1268 for examples of `Pytree.const`. Please re-open if this doesn't help.
