### ISSUE TITLE
[Defactor] Mapping over single inbuilt/custom distributions

### ISSUE THREAD

**Issue by arijit-dasgupta** [genjax-community/genjax#669]
```python
@genjax.gen
def model_outer():
    x = model_inner_map(jnp.zeros(100),0,1) @ "x"
    return x

model_inner_map = genjax.MapCombinator.new(genjax.gen(lambda *x : genjax.normal(*x[1:]) @ "x_inner"), in_axes=(0,None,None))
```

If I write a model where I want to independently sample from a 100 gaussians, I can do the above which runs the map combinator. To access the value, I have to do the following:

```python
key = jax.random.PRNGKey(1111)
tr = model_outer.simulate(key,())
tr["x", "x_inner"]
```

I have to use `tr["x", "x_inner"]` to get the sampled values of length 100. This makes sense as Map is used over a generative function, and I need to give the `@"x_inner"` address for me to access the values in the `VectorChoiceMap` (`tr["x"]`). This design choice makes sense as Unfold and Map both map run over functions that make multiple random choices, hence the need to address twice is very intuitive. However it would be nice if there was a way to use a Map combinator elegantly over a single distribution (inbuilt or custom). So instead of:

```python
model_inner_map = genjax.MapCombinator.new(genjax.gen(lambda *x : genjax.normal(*x[1:]) @ "x_inner"), in_axes=(0,None,None))
```

it could just be 
`model_inner_map = genjax.XXXX(genjax.normal)`

where `XXXX` is just a placeholder for some DistributionMap type function. This function would assume all arguments of `genjax.normal` will have `in_axes` values of 0 (Or maybe not, if we want to sample with different arguments), and it is vectorizing it over a bunch of subkeys. Then the step where we sample would look more like:

`x = model_inner_map(subkeys, 0, 1) @"x"`

I'm not sure if it should be subkeys, or just 100 or `jnp.zeros(100)`. 

To get the values, it would be simply tr["x"]. I'm not sure if this fits into the design philosophy of how you use `VectorChoiceMap`. I'm just thinking about using a Map over a single distribution easily and access it via the trace directly with the Map's address (as there is only one set of vectorized choices). 

Otherwise, this generative function with a lambda inside of it works fine. Would be nice to hear your thoughts on the value of this.

**Comment by MathieuHuot** [comment]
@arijitnoobstar @femtomc I'll close this as this was essentially fixed in 0.4 with the new combinator system.
