### ISSUE TITLE
Go through and fill in the boilerplate to make each distribution a `GenerativeFunction`

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#8]
Core functionality implemented in #6, a few distributions transferred over already (for tests), rest need to be converted.

**Comment by alex-lew** [comment]
@femtomc All this boilerplate doesn't seem ideal. Why not create a `class Distribution(GenerativeFunction)` that contains automated implementations of the GFI based on user-defined `random` and `logpdf` methods? This way the distribution definitions look pretty much the same (you just need to declare them all as subclasses of `Distribution`), but behind the scenes they are treated as generative functions.

**Comment by femtomc** [comment]
@alex-lew this is a good idea, and likely the pythonic way to handle this.

as you look through the code, make sure to keep tabs on things that seem inelegant — I’m a bit of a novice in terms of organizing a Python codebase.

**Comment by femtomc** [comment]
Closing as completed.
