### ISSUE TITLE
[Defactor] replace `abc.abstractmethod`

### ISSUE THREAD

**Issue by littleredcomputer** [genjax-community/genjax#802]
We were never getting the benefit of it because ABC was not used as a metaclass at the root of the type hierarchy (see [here](https://docs.python.org/3/library/abc.html#abc.abstractmethod)). 

We do however want the type safety, so use `typing.override` instead.

**Comment by femtomc** [comment]
Can we make the base metaclasses (like `Pytree` inheritors of ABC)?

**Comment by littleredcomputer** [comment]
This got fixed when equinox.Module became a base class of Pytree: it pulls in ABC as a metaclass and so abstractmethod enforcement is now working.
