### ISSUE TITLE
[Defactor] reconsider direct invocation of generative functions

### ISSUE THREAD

**Issue by littleredcomputer** [genjax-community/genjax#866]
Before version 0.1.0, generative functions (either Static or Interpreted) had two `__call__` methods, switched via `plum.dispatch`: one (the normal case) to produce a `SugaredGenerativeFunctionCall` which must be paired via the `@` or `__matmul__` operator to form a call to trace.

Developers of generative functions asked for a shortcut to calling `gf.simulate(key, args)`, which the other method provided in the form of a (key, args) signature. 

Having two ways of being `Callable` via `plum` confuses IDEs, so we decided to move the second form to a new method `gf.apply(key, args)` where (as before) the args are provided in a tuple (hinted at by the name `apply`.

It's worth noting that there is a point of view in which a generative function should not be called on its own, that rather it should be explicitly driven by a process like simulate. Moving to `apply` makes this process slightly more apparent

We will revisit this decision, hopefully with the benefit of customer feedback

**Comment by sritchie** [comment]
Something close to this view won the day:

> It's worth noting that there is a point of view in which a generative function should not be called on its own, that rather it should be explicitly driven by a process like simulate. Moving to `apply` makes this process slightly more apparent

Passing arguments to a generative function now returns a `GenerativeFunctionClosure`, which can by invoked by passing a key.

We'll add a cookbook entry showing how to invoke a `GenerativeFunctionClosure` in nightly/0.4.0.

**Comment by sritchie** [comment]
Closed in favor of an internal Linear issue for a cookbook entry.
