### ISSUE TITLE
[Defactor] consider evicting `scipy` dependency

### ISSUE THREAD

**Issue by littleredcomputer** [genjax-community/genjax#871]
JAX comes with its own reimplementation of the linear algebra part of `scipy`. The only function from there that we call is `circulant` which we could easily supply in the demo where it's used. Installing genjax from `pypi` suggests that `scipy` is a pretty heavy dependency for one function.

**Comment by femtomc** [comment]
Completely with you. Let's kill it. I've only been burned by `scipy` as a dep in the past 😆.

**Comment by sritchie** [comment]
Let's take this further and see if there are any other dependencies we can lose or slim down. Dropping scipy is a big win, nice find @littleredcomputer

**Comment by femtomc** [comment]
We don't actually have `scipy` in the `pyproject.toml`...

**Comment by littleredcomputer** [comment]
It's in requirements.txt ... but I'm not sure if poetry reads that? I know pip is installing it, so I'll do some digging

**Comment by littleredcomputer** [comment]
Jax itself pulls it in, it looks like it won't be easy to dislodge after all:
```
pipdeptree|grep scipy
Warning!! Cyclic dependencies found:
* conda-libmamba-solver => conda => conda-libmamba-solver
* conda => conda-libmamba-solver => conda
------------------------------------------------------------------------
│   │   └── scipy [required: >=1.9, installed: 1.11.4]
│   └── scipy [required: >=1.9, installed: 1.11.4]
│   │   │   └── scipy [required: >=1.9, installed: 1.11.4]
│   │   │   └── scipy [required: >=1.9, installed: 1.11.4]
│   │   └── scipy [required: >=1.9, installed: 1.11.4]
│   │   └── scipy [required: >=1.9, installed: 1.11.4]
```
