### ISSUE TITLE
[GJEP] `RepeatCombinator` taking a shape not just an integer.

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#887]
I would like to call `RepeatCombinator` with a shape e.g. `(n,k)` to create a sample array of shape `(n,k,...)`.
At the moment I have to do

```
colors = RepeatCombinator(N*K, genjax.uniform)(0.0,1.0) @ "x"
colors = colors.reshape((N,K))
```

**Comment by sritchie** [comment]
Closing this as a duplicate / related to #493 . We'll either document this or add this as a convenience approach on top of the current code in `nightly`. Thanks @mirkoklukas !
