### ISSUE TITLE
[Docs] Docstring for genjax distributions, eg. genjax.bernoulli

### ISSUE THREAD

**Issue by mirkoklukas** [genjax-community/genjax#902]
Currently the signature spits out:

```
Signature:   genjax.bernoulli(*args: Any, **kwargs) -> genjax._src.generative_functions.supports_callees.SugaredGenerativeFunctionCall
```

**Comment by sritchie** [comment]
We'll take this on, @mirkoklukas ! I solved something similar for `@genjax.gen`... this will be a bit trickier but a good idea to somehow get this exposed.

**Comment by sritchie** [comment]
Actually! It looks like @femtomc has already solved this in editors like VSCode by adding docstrings to everything.

This is not going to be able to work with, e.g., `help(genjax.normal)`.

@mirkoklukas how are you accessing docstrings? do you see this working now?

<img width="755" alt="image" src="https://github.com/user-attachments/assets/c9fa7114-59d7-4dca-94d7-49385cf77f59">
