### ISSUE TITLE
[Defactor] Improve choicemap console printouts

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#916]
Here is an example printout of a choicemap from the GenJAX console:
```
(HierarchicalChoiceMap)
├── :camera_pose
│   └── (ValueChoice)
│       └──  f32[4,4]
├── :contact_params_0
│   └── (ValueChoice)
│       └──  f32[3]
├── :id_0
│   └── (ValueChoice)
│       └──  i32[]
├── :image
│   └── (ValueChoice)
│       └──  f32[48,64,3]
...
```

I propose that we should change the console so the default printout looks like
```
├── "camera_pose"
 │  └──  Array([[1., 0., 0., 0.],
 │              [0., 1., 0., 0.],
 │              [0., 0., 1., 0.],
 │              [0., 0., 0., 1.]], dtype=float32)
 │
├── "contact_params_0"
 │  └──  Array([ -8.749392 ,  -6.0559587, -45.552917 ], dtype=float32)
 │
├── "id_0"
 │  └── Array(3, dtype=int32)
 │
├── "image"
│       └──  Array(shape=(48, 64, 3), dtype=float32)
```
or
```
├── "camera_pose"
 │  └──  f32[[1., 0., 0., 0.],
 │           [0., 1., 0., 0.],
 │           [0., 0., 1., 0.],
 │           [0., 0., 0., 1.]]
 │
├── "contact_params_0"
 │  └──  f32[ -8.749392 ,  -6.0559587, -45.552917 ]
 │
├── "id_0"
 │  └── int32: 3
 │
├── "image"
│       └──  f32(shape=(48, 64, 3))[...]
```

We should discuss the exact design.  The key changes are:
- By default, print the values in the choicemap, for arrays below a given size.  (E.g. maybe all arrays with < 20 elements should be rendered by default.). For large arrays (like the "image") I think it makes sense to have the default not print the whole thing.
- By default, elide the "HierarchicalChoiceMap" / "ValueChoiceMap" / etc. labels.
- Display the addresses as strings, if they are actually string datatypes.  (Don't write `:address` if the python value is actually `"address"`.)

It may also be good to include an interface in the GenJAX console so that users can specify in a little bit more detail what they want the printout to look like.  Things which they should perhaps be able to customize:
- The array size at which the console stops printing values and starts printing datatypes
- Does the user want printouts of the ChoiceMap types (ValueChoiceMap, HierarchicalChoicemap, etc.) or should these be elided (as by default)
- [...we can brainstorm others...]

@femtomc @littleredcomputer What do you think of this?  If you agree that it would be good to improve the choicemap displays, I propose that we iterate on a design spec for this in this issue (or elsewhere if that is better), and discuss an implementation plan at the OpenGen meeting on Wednesday Feb 7.

**Comment by littleredcomputer** [comment]
This has been a pain point and I agree that hiding scalars and not even providing a segment of array values is a mistake

**Comment by sritchie** [comment]
Closed in favor of the penzai integration, currently in nightly, docs coming.
