### ISSUE TITLE
[BUG] Unexpected projected score for a MapTrace containing a MapTrace

### ISSUE THREAD

**Issue by jburnim** [genjax-community/genjax#939]
**Describe the bug**

When I run the following code:
```python
@genjax.map_combinator(in_axes=(0,))
@genjax.map_combinator(in_axes=(0,))
@genjax.static_gen_fn
def f(x):
    return genjax.normal(x, 0.1) @ 'y'

key = jax.random.PRNGKey(314159)
fn = jax.jit(f.simulate)
key, sub_key = jax.random.split(key)
tr = fn(sub_key, (jnp.arange(15.0).reshape((3, 5)),))

projected_score = tr.project(
    genjax.indexed_select(
        jnp.array([1, 2]),
            genjax.indexed_select(jnp.array([[1, 2, 4], [0, 2, 3]]))))
```
on GenJAX `nightly`, I get a `projected_score` of 0.0.

**To reproduce**

Check out the branch `jburnim_test_cases` and run the added test case -- see https://github.com/probcomp/genjax/compare/nightly...jburnim_test_cases?expand=1 .

**Expected behavior**

I don't understand the semantics of this kind of nested projection.

But, whatever the intended semantics, I think it is unlikely the current behavior of the code is expected.  In particular, in the current code:

 1. The outer `MapTrace.project` calls `MapTrace.project` on its inner trace with indices `[[1, 2, 4], [0, 2, 3]]`.
 2.  The inner `MapTrace.project` calls `jnp.take` on the scores array (of shape `(3, 5)`) with the indices `[[1, 2, 4], [0, 2, 3]]` -- which flattens the scores, takes indices [1, 2, 4, 0, 2, 3] from the flattened array -- and then returns the sum of the result.
 3. The outer `MapTrace.project` then calls `jnp.take` on the returned scalar projected score with indices `[1, 2]` (and `fill=0.0`) -- which will results in `[0.0, 0.0]` -- and then returns the sum of this array.

**Execution environment (please complete the following information):**
 - OS: Debian 10 -- 4.19.0-26-cloud-amd64 #1 SMP Debian 4.19.304-1 (2024-01-09) x86_64 GNU/Linux
 - Python version: 3.11.6
 - GenJAX version: nightly at c53ef1e5eaa0d88f72342bb7e8a8897e79afb175

cc @midfield

**Comment by jburnim** [comment]
As discussed offline with @femtomc , I'm opening this issue to discuss what behavior we want for this case.

One possible behavior for `MapTrace.project` (given an indexed selection `idx`) would be to do something like:

 1. `vmap` over the inner trace's `project` function (with in_axes of 0 for the the self/trace argument and for the selection argument) -- and call the vmapped inner function on the inner trace and the inner selection (`idx.inner`).
 2. The returned, projected score will then be a vector, and we can take the indices corresponding to the indexed selection `idx` and then sum the taken elements.

**Comment by sritchie** [comment]
This should be fixed by our new design in nightly, but we'll need to check and get a test in. Thanks for the report, Jacob!

**Comment by sritchie** [comment]
Closing, let's re-open if we can get a repro with the current `main`.
