### ISSUE TITLE
[BUG] IndexedSelection.get_subselection() refers to non-existent dataclass field

### ISSUE THREAD

**Issue by ahiser1117** [genjax-community/genjax#950]
**Describe the bug**
`get_subselection` function of `IndexedSelection` refers to the field "`index_selection`" on Line 75 of `vector_datatypes.py`. This field does not exist and throws an error.

**To Reproduce**
Attempt to run the function `get_subselection` on an `IndexedSelection`

**Expected behavior**
Get the subselection without error

**Comment by ahiser1117** [comment]
Not sure if this is the desired solution but I was able to get the behavior I was looking for by simply exchanging `index_selection` with `inner`.  

Although I'd imagine you're looking for a more nuanced solution that allows for picking particular indices, this temporary solution works for me.

**Comment by femtomc** [comment]
@ahiser1117 Thanks for reporting this. We'll look at this as part of a detailed review of `Selection` in our current push. Stay tuned.

**Comment by sritchie** [comment]
Fixed on the upcoming 0.4.0 release (currently merged to nightly). Release coming soon.
