### ISSUE TITLE
[Defactor] Provide an easily usable way of specifying new choice map updates from a given trace

### ISSUE THREAD

**Issue by femtomc** [genjax-community/genjax#952]
This is part of usability.

If I have a trace in hand from a large model, I may want to use the address space of its choice map as a type of "reference" to create new choice map constraints (for e.g. `update`, or `importance` interface invocations).

There should be a way to do this which builds in a compositional way on `Selection` interfaces and their interaction with choice map.

**Comment by sritchie** [comment]
I think we can do this now with `.at`, right?
