### ISSUE TITLE
[GJEP] Add `choicemap.to_selection`

### ISSUE THREAD

**Issue by georgematheos** [genjax-community/genjax#964]
Potentially useful feature: have a function that takes a choicemap, and returns a selection which selects exactly the set of addresses in that choicemap.

**Comment by femtomc** [comment]
Look up `get_selection` in the codebase.

**Comment by femtomc** [comment]
Closed, as supported by existing implementation. We'll continue working on this in https://github.com/probcomp/genjax/pull/1018.
